Fix failing test because of bad implicit cast
DocumentSpec > Cannot set created FAILED
    org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object '{@type=Publication, place={@type=Place, label=Stuttgart}, agent={@type=Agent, label=Thieme}}' with class 'java.util.LinkedHashMap' to class 'java.util.Collection' due to: groovy.lang.GroovyRuntimeException: Could not find matching constructor for: java.util.Collection(LinkedHashMap)
        at whelk.converter.marc.MarcFieldHandler.convert_closure15(MarcFrameConverter.groovy:2145)
        at groovy.lang.Closure.call(Closure.java:418)
        at whelk.converter.marc.MarcFieldHandler.convert(MarcFrameConverter.groovy:2128)
        at whelk.converter.marc.MarcRuleSet.processFields_closure6(MarcFrameConverter.groovy:756)
        at groovy.lang.Closure.call(Closure.java:418)
        at whelk.converter.marc.MarcRuleSet.processFields(MarcFrameConverter.groovy:753)
        at whelk.converter.marc.MarcRuleSet.convert(MarcFrameConverter.groovy:746)
        at whelk.converter.marc.MarcConversion.convert(MarcFrameConverter.groovy:274)
        at whelk.converter.marc.MarcFrameConverter.runConvert(MarcFrameConverter.groovy:81)
        at whelk.converter.marc.MarcFrameConverter.convert(MarcFrameConverter.groovy:107)
        at whelk.DocumentSpec.Cannot set created(DocumentSpec.groovy:374)